apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-pvc
  namespace: milvus-service
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
