apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-pvc
  namespace: milvus-service
spec:
  storageClassName: ibmc-block-gold
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
